server:
  port: 9091
  servlet:
    context-path: /JpaDemo
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/user_demo?zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      database: mysql
      show-sql: true
  main:
    allow-bean-definition-overriding: true